version: '2.1'

services:
  nginx:
    image: ghcr.io/wouterds/next-base/nginx
    container_name: be.wouterds-nginx
    restart: unless-stopped
    mem_limit: 32mb
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=reverse-proxy'
      - "traefik.http.routers.bewouterds-http.entrypoints=web"
      - "traefik.http.routers.bewouterds-http.rule=Host(`wouterds.be`)"
    networks:
      - default
      - reverse-proxy

  node:
    image: ghcr.io/wouterds/next-base/node
    container_name: be.wouterds-node
    restart: unless-stopped
    mem_limit: 128mb

networks:
  reverse-proxy:
    external: true
