name: docker-image

on:
  workflow_run:
    branches:
      - main
    workflows:
      - code-review
    types:
      - completed

env:
  REGISTRY: ghcr.io
  USER: ${{ github.actor }}
  PASS: ${{ secrets.GITHUB_TOKEN }}
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker-image:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v2

      - name: 'Docker: registry login'
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.USER }}
          password: ${{ env.PASS }}

      - name: 'Docker: build & push nginx image'
        uses: docker/build-push-action@v2
        with:
          file: .docker/nginx/Dockerfile
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/nginx

      - name: 'Docker: build & push node image'
        uses: docker/build-push-action@v2
        with:
          file: .docker/node/Dockerfile
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/node
